### ISSUE TITLE
No instrumentation detected 

### ISSUE THREAD

**Issue by alimubasshira** [shijy16/WDFuzzer#1]
I have used the release of WDFuzzer to fuzz my target application and getting the following error.
 PROGRAM ABORT : No instrumentation detected
         Location : perform_dry_run(), D:\code\WDFuzzer\winafl\afl-fuzz.c:3044
Earlier, too i got the same error, it pointed that debug folder was missing, so i renamed release folder as debug, in which dynamorio.dll is present, but the issue remains the same.

**Comment by shijy16** [comment]
Any details about the command line you were trying to run?

**Comment by alimubasshira** [comment]
afl-fuzz.exe -i D:\fuzzing\WDFuzzer-x86_v1.0\demo\in -o D:\fuzzing\WDFuzzer-x86_v1.0\demo\out -D D:\fuzzing\WDFuzzer-x86_v1.0\drmemory\build32\dynamorio\bin32 -R D:\fuzzing\WDFuzzer-x86_v1.0\drmemory\build32\bin -t 10000 -O target_out -N -- -coverage_module target.exe -coverage_mode edge -- D:\fuzzing\WDFuzzer-x86_v1.0\demo\target.exe -in D:\fuzzing\WDFuzzer-x86_v1.0\demo\in -out target_out

**Comment by alimubasshira** [comment]
does WDfuzzer have capability to discover bugs that could not be discovered using WinAfl

**Comment by shijy16** [comment]
The last part of the command line seems wrong. You have to replace the input file with '@@' like the example `target.exe -out target_out @@`. `@@` tells the fuzzer to replace it with fuzzing inputs.

**Comment by shijy16** [comment]
> does WDfuzzer have capability to discover bugs that could not be discovered using WinAfl

Technically it dose. It requires the debug information, and use it to discover memory bugs with drmemory. While WinAFL doesn't require debug information, thus ignores most memory bugs.

**Comment by alimubasshira** [comment]
Thank you.

**Comment by shijy16** [comment]
You are welcome.
